### PR TITLE
object: fix Change.Files() method behavior (fix #317)

### LINKED ISSUE #317: "object not found" error in `object.Change#Files()` when `To` is a submodule
Discovered after updating to the latest version of `gopkg.in/src-d/go-git.v4`

I use `object#DiffTree()` and step through the changes, unconditionally calling `change.Files()` for each. When I come across the addition of a submodule, I get the aforementioned error, when before I would not.

Does it make more sense for `File()` to return `nil` instead for these cases? Presumably there's a similar issue with the `From` side as well.

### PR DESCRIPTION
**Pull request by ajnavarro**
- If 'from' or 'to' are tree entries that aren't files, Files() method will return nil instead of object not found error.
- Added a test checking this using modules fixture.

### CODE REVIEW

**Comment by ajnavarro** [comment]
Please, merge https://github.com/src-d/go-git-fixtures/pull/4 first.

File: plumbing/object/change.go [hunk 1]
```diff
@@ -61,6 +70,12 @@ func (c *Change) Files() (from, to *File, err error) {
 	return
 }
 
+func isInvalidFileMode(t TreeEntry) bool {
```
Comment (mcuadros) [inline plumbing/object/change.go]: Please use the FileMode methods: https://godoc.org/gopkg.in/src-d/go-git.v4/plumbing/filemode

I think that is this method can be replaced with a call to `FileMode.IsRegular()`

Comment (ajnavarro) [inline plumbing/object/change.go]: @mcuadros I think `FileMode.IsRegular()` doesn't cover all the cases, like executable files. Maybe @alcortesm could do us some hints.

Comment (mcuadros) [inline plumbing/object/change.go]: Then you have `IsFile`. Why the symlink is being skip, is a regular file.

Comment (alcortesm) [inline plumbing/object/change.go]: Use `Filemode.IsFile()`, that's what @santi and me agreed when I answered https://github.com/src-d/go-git/issues/317.

Comment (smola) [inline plumbing/object/change.go]: @alcortesm It's @smola ;-)

Comment (alcortesm) [inline plumbing/object/change.go]: lol, sorry!

Comment (smola) [inline plumbing/object/change.go]: Right. I was confused when we talked this morning.
@ajnavarro Symlinks can be returned by Files()
