### PR TITLE
fixtures: support more than one source folder (fix #217)

### LINKED ISSUE #217: fixtures.Init() fails when there are multiple directories in GOPATH
```
exit status 2
	panic: open /home/smola/dev/go:/home/smola/dev/go/src/gopkg.in/src-d/go-git.v4/fixtures/data/git-7a725350b88b05ca03541b59dd0649fda7f521f2.tgz: no such file or directory
```

`fixtures.Init()` is incorrect when there are multiple directories in GOPATH.

### PR DESCRIPTION
**Pull request by ajnavarro**
GOPATH can contain more than one folder separated by ':'. To check it correctly,
we use SrcDirs() method to be able to check into all the source folders if
fixtures exists.

### CODE REVIEW

File: fixtures/fixtures.go [hunk 1]
```diff
@@ -11,6 +11,7 @@ import (
 	"gopkg.in/src-d/go-git.v4/plumbing"
 
 	"github.com/alcortesm/tgz"
+	"github.com/pkg/errors"
```
Comment (smola) [inline fixtures/fixtures.go]: "errors"

File: fixtures/fixtures.go [hunk 2]
```diff
@@ -265,11 +266,22 @@ func (g Fixtures) Exclude(tag string) Fixtures {
...
-	)
+func Init() error {
+	srcs := build.Default.SrcDirs()
+
+	for _, src := range srcs {
+		rf := filepath.Join(
+			src, "gopkg.in/src-d/go-git.v4", "fixtures",
+		)
+
+		_, err := os.Stat(rf)
```
Comment (smola) [inline fixtures/fixtures.go]: single line if
